BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"UserID"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	UNIQUE("Username"),
	PRIMARY KEY("UserID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Hour" (
	"HourID"	INTEGER NOT NULL UNIQUE,
	"Year"	INTEGER NOT NULL,
	"Month"	INTEGER NOT NULL,
	"Day"	INTEGER NOT NULL,
	"Hour"	INTEGER NOT NULL,
	PRIMARY KEY("HourID" AUTOINCREMENT)
);
COMMIT;
